"""empty message

Revision ID: d98960495696
Revises: f9171c5f78c1
Create Date: 2022-12-23 18:10:05.477593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98960495696'
down_revision = 'f9171c5f78c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Fichier', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Fichier', 'url')
    # ### end Alembic commands ###
