"""empty message

Revision ID: f9171c5f78c1
Revises: e0e0790c11ff
Create Date: 2022-12-23 18:05:34.078353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9171c5f78c1'
down_revision = 'e0e0790c11ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Fichier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('acivite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acivite_id'], ['Activite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Activite', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Activite', 'Service', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Activite', type_='foreignkey')
    op.drop_column('Activite', 'service_id')
    op.drop_table('Fichier')
    # ### end Alembic commands ###
